server:
  port: 9003

spring:
  application:
    name: eureka-ribbon-hystrix

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka/


#eureka-provider:
#  ribbon:
#    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
#    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
#    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
#    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 最空闲连接策略
#    ConnectTimeout: 500 #请求连接超时时间
#    ReadTimeout: 1000 #请求处理的超时时间
#    OkToRetryOnAllOperations: true #对所有请求都进行重试
#    MaxAutoRetriesNextServer: 2 #切换实例的重试次数


#    Hystrix熔断机制   HyStrix相关所有配置连接： https://www.cnblogs.com/duan2/p/9302431.html

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000    # 根据Ribbon的超时时间设置 且Ribbon的Max重试为1  所以 6000 * (1+1)


ribbon:
  ReadTimeout: 6000                 # 针对每一个Broker设置的时间
  ConnectTimeout: 6000              # 针对每一个Broker设置的时间
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1